/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x1A, 0x42, 0xD5, 0xFD, 0x12, 0x4A, 0x10, 0x0D}
#define ENCODERS_PAD_A { D6, D1 }
#define ENCODERS_PAD_B { D4, D2 }

/* WS2812 RGB LEDs */
#define WS2812_DI_PIN D0
#define RGBLED_NUM 12 // Number of LEDs
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_SNAKE

#define VIAL_COMBO_ENTRIES 15
#define VIAL_TAP_DANCE_ENTRIES 15
